//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interdisciplinar2.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
#pragma warning disable CS0649 // Campo "Settings.Theme" nunca é atribuído e sempre terá seu valor padrão null
        internal readonly string Theme;
#pragma warning restore CS0649 // Campo "Settings.Theme" nunca é atribuído e sempre terá seu valor padrão null

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
